/** Public-site copy. Product workflows remain in the original application. */
export const assets = {
  logo: '/website/logo-symbol.png',
  family: '/website/generated/support-family.webp',
  everyday: '/website/generated/support-safety.webp',
  journey: '/website/generated/support-travel.webp',
};

export const solutions = [
  { slug: 'personal-safety', icon: 'shield', label: 'Personal safety', tag: 'A little confidence. Everywhere.', title: 'Your everyday. A little safer.', description: 'Keep your trusted contacts, SOS tools and location sharing in one place. For the late ride home, the solo journey and everything in between.', image: 'everyday', app: '/safety', features: [ ['SOS & emergency contacts', 'Reach the people you have chosen when you need their attention.'], ['Location sharing', 'Share your location with your circle when you choose to enable it.'], ['Siren & safety tools', 'Find your in-app siren and safety tools together, without searching through different screens.'], ['Check in with your people', 'Make a quick check-in part of your everyday routine.'] ], note: 'Nek Sathi is a safety companion, not an emergency-response service. Alerts depend on connectivity, permissions and your contacts being available.' },
  { slug: 'family-guardian', icon: 'users', label: 'Family Guardian', tag: 'Close, even when you are apart.', title: 'Your people. One caring circle.', description: 'Bring your family together with location sharing, check-ins and a shared place for the moments that matter.', image: 'family', app: '/family', features: [ ['A shared family map', 'See the location updates shared by members of your circle.'], ['Thoughtful check-ins', 'Ask “Are you okay?” and let your family know how you are doing.'], ['Places & alerts', 'Use supported place alerts with the necessary location permissions enabled.'], ['Your circle, your choice', 'Invite your trusted people and review who can see your information.'] ], note: 'Family members must join and grant the permissions needed for the features they use. Location freshness depends on the device and connection.' },
  { slug: 'smart-qr', icon: 'qr', label: 'Smart QR', tag: 'Small code. Meaningful connection.', title: 'A simple scan. A helpful connection.', description: 'Connect your belongings to you with Smart QR tags. Give a finder a way to reach the right person through a scan.', image: 'journey', app: '/tags', features: [ ['Tags for everyday things', 'Create tags for bags, luggage, pets and other supported items.'], ['A helpful scan page', 'A scan opens the public page linked to the tag.'], ['Contact through the platform', 'Use the contact and alert options available for your tag and account.'], ['Manage your details', 'Keep the information attached to your QR tag up to date.'] ], note: 'QR tags are not GPS trackers. Information shown to a person scanning a tag depends on the profile and settings you configure.' },
  { slug: 'vehicle-safety', icon: 'car', label: 'Vehicle safety', tag: 'Park with a little more peace of mind.', title: 'Give your vehicle a voice.', description: 'A QR sticker makes it easier for someone to report a blocked vehicle, a parking concern or an incident to the owner.', image: 'journey', app: '/dashboard', features: [ ['A QR for your vehicle', 'Register your vehicle and manage its linked QR.'], ['Parking & incident reports', 'Let a scanner report a concern using the vehicle’s scan page.'], ['Emergency contacts', 'Maintain the contacts associated with your vehicle.'], ['Your alert history', 'Review incoming alerts and related incident information from your account.'] ], note: 'A QR sticker does not track a vehicle by itself or guarantee incident detection. A person must scan and submit a report.' },
  { slug: 'anti-theft', icon: 'lock', label: 'Device protection', tag: 'A more prepared digital life.', title: 'Be ready for the unexpected.', description: 'Keep your registered devices, supported anti-theft tools and lost-phone guidance organised in one place.', image: 'everyday', app: '/theft-protection', features: [ ['Your device registry', 'Maintain a record of the devices linked to your account.'], ['Supported security tools', 'Use available alarm and device-protection controls on supported devices.'], ['Incident information', 'Review device events and evidence that your setup makes available.'], ['Lost-phone guidance', 'Find your stolen-phone reporting guide in the application.'] ], note: 'Remote lock, camera capture, SIM alerts and other device actions are platform-dependent. They require supported native capabilities, permissions and configuration; they are not guaranteed in a web browser.' },
  { slug: 'digital-cards', icon: 'card', label: 'Digital safety cards', tag: 'Important information, easier to find.', title: 'A small card. The details that matter.', description: 'Create digital cards to bring useful contact and emergency information together in an accessible profile.', image: 'family', app: '/cards', features: [ ['Your digital profile', 'Create and manage the information you choose to add to a card.'], ['Emergency details', 'Keep relevant emergency-contact information easy to find.'], ['Scan to open', 'Share the card’s QR so others can open its public page.'], ['Keep it current', 'Update your card details from your account when things change.'] ], note: 'Only add information you are comfortable making available through the public card. A safety card does not replace medical advice or professional care.' },
  { slug: 'temporary-circles', icon: 'clock', label: 'Temporary circles', tag: 'Together, just for the journey.', title: 'A circle for this moment.', description: 'Create a temporary circle for a journey, an outing or a shared plan, without making it your permanent family group.', image: 'journey', app: '/circles', features: [ ['A circle for a plan', 'Set up a group around a particular trip or occasion.'], ['Invite the right people', 'Share the invitation with the people taking part.'], ['Time-bound sharing', 'Use the time controls available for your circle.'], ['Review your sharing', 'Check participants and sharing settings when your plans change.'] ], note: 'Participants need to accept the invitation and enable the permissions required for sharing.' },
  { slug: 'community-safety', icon: 'heart', label: 'Community & alerts', tag: 'Care goes a little further, together.', title: 'Look out for your everyday world.', description: 'Keep track of your safety alerts, review reported incidents and explore the community features in Nek Sathi.', image: 'family', app: '/community', features: [ ['Your alert feed', 'Find incoming safety and QR-related alerts in one place.'], ['Incident records', 'Review the reports associated with your account.'], ['Community information', 'Explore the local safety information available in the community section.'], ['A route to support', 'Raise a support request when you need help using the platform.'] ], note: 'Community information is not a verified emergency-dispatch feed. Check the context and contact local emergency services when immediate help is needed.' },
];

export const audiences = [
  { slug:'families', label:'For families', icon:'users', title:'More connected. Less “where are you?”', description:'From school pick-ups to weekend plans, bring the people you care about into one trusted circle.', image:'family', benefits:['A family circle with invited members','Permission-based location sharing','Everyday check-ins and safety contacts'], related:['family-guardian','personal-safety','temporary-circles'] },
  { slug:'schools', label:'For schools', icon:'school', title:'Little journeys. A little more care.', description:'Explore Smart QR IDs and guardian contact profiles for your school community, with a clear onboarding and privacy process.', image:'family', benefits:['Student and guardian QR profiles','Bulk tag onboarding for your organisation','Staff access through the organisation portal'], related:['smart-qr','digital-cards','family-guardian'] },
  { slug:'hospitals', label:'For hospitals & care', icon:'heart', title:'A helpful connection when it matters.', description:'Explore digital emergency information and guardian-contact profiles for care settings. Configure what is shared before issuing a card or tag.', image:'family', benefits:['Emergency-contact profiles','QR cards and supported care tags','An organisation workspace for your team'], related:['digital-cards','smart-qr','personal-safety'] },
  { slug:'offices', label:'For offices', icon:'briefcase', title:'Care for your team. And their things.', description:'Bring recoverable staff assets, contact profiles and bulk QR onboarding into your workplace.', image:'journey', benefits:['Recoverable staff badges and assets','Bulk QR tag management','Dedicated organisation access'], related:['smart-qr','digital-cards','vehicle-safety'] },
  { slug:'travellers', label:'For travellers', icon:'compass', title:'Go a little further. Stay a little closer.', description:'Keep trusted people in the loop, create a temporary circle and add a Smart QR tag to the things travelling with you.', image:'journey', benefits:['Temporary circles for shared trips','QR tags for luggage and belongings','SOS contacts and location sharing'], related:['temporary-circles','smart-qr','personal-safety'] },
];

export const faqs = [
  { category:'Getting started', q:'What is Nek Sathi?', a:'Nek Sathi brings personal safety tools, family sharing, Smart QR tags, vehicle alerts and digital safety cards into one platform. Choose the features that fit your everyday life.' },
  { category:'Getting started', q:'How do I get started?', a:'Create an account, complete your profile and add your trusted contacts. Then set up a family circle, register a vehicle or create a QR tag. Allow only the permissions needed for the features you choose.' },
  { category:'Smart QR', q:'Does a Smart QR tag track my belongings?', a:'No. A QR tag is not a GPS tracker. It opens the linked profile when someone scans it, allowing that person to use the contact or report options configured for the tag.' },
  { category:'Privacy', q:'Who can see my location and QR profile?', a:'Location sharing depends on your circle membership, settings and device permissions. A person scanning a public QR can see the information configured for that public profile. Review your settings before sharing a tag or card.' },
  { category:'Safety', q:'Does SOS work without a connection?', a:'Sending alerts and updating shared location generally require connectivity and the necessary permissions. Delivery also depends on your contacts and configured notification services. Do not rely on the app as your only way to request urgent help.' },
  { category:'Getting started', q:'Can I use Nek Sathi on my computer?', a:'You can open the web application in a browser. Camera, location, notifications and device-protection features depend on the browser, device and permissions. Native-only features may not be available on the web.' },
  { category:'Safety', q:'Are all device-protection features available on every phone?', a:'No. Remote device actions, background services and evidence capture depend on supported native capabilities, permissions and configuration. Check availability on your specific device.' },
  { category:'Organisations', q:'Can a school or business request QR tags in bulk?', a:'Yes. Use the contact form and choose a bulk QR or organisation enquiry. Share the intended use and approximate quantity so the team can discuss onboarding and requirements.' },
  { category:'Privacy', q:'How do I request account deletion?', a:'Read the account-deletion page for the existing account-removal instructions and contact route. Review what removing your account means for your linked tags, cards and circles.' },
];
