/** Edit slider copy/order here. Scenes are original illustrations, not incident footage. */
export const stories = [
  { id:'road', number:'01', label:'On the road', eyebrow:'VEHICLE QR · EMERGENCY CONTACTS', title:['A small scan.','A moment that','matters.'], accent:2, description:'An unexpected stop. A helpful stranger. Give someone a way to reach the right people when your vehicle needs attention.', hindi:'एक छोटा सा स्कैन। एक ज़रूरी कनेक्शन।', cta:'Explore vehicle safety', to:'/solutions/vehicle-safety', event:'A concern on the road', action:'Scan the vehicle QR', result:'Reach the registered contacts', cardLabel:'A HELPFUL CONNECTION', cardTitle:'The right people. Within reach.', icon:'car' },
  { id:'theft', number:'02', label:'A missing phone', eyebrow:'DEVICE PROTECTION · LOST-PHONE GUIDANCE', title:['Your phone is gone.','Your next step','isn’t.'], accent:2, description:'Prepare your device, set up supported security tools and find your lost-phone guidance in one place. A little preparation matters.', hindi:'फोन गुम हो जाए, तो अगला कदम पता हो।', cta:'Explore device protection', to:'/solutions/anti-theft', event:'A phone goes missing', action:'Use your prepared tools', result:'Review the reporting guide', cardLabel:'PREPARE YOUR DEVICE', cardTitle:'Know what to do next.', icon:'lock' },
  { id:'family', number:'03', label:'Family journeys', eyebrow:'FAMILY GUARDIAN · CHOSEN LOCATION SHARING', title:['Different journeys.','One circle','of care.'], accent:2, description:'The school run. The commute. The late journey home. Bring the people you trust together, with sharing that starts with their choice.', hindi:'रास्ते अलग हों, साथ बना रहे।', cta:'Meet Family Guardian', to:'/solutions/family-guardian', event:'Your people head out', action:'Share with your circle', result:'Check in along the way', cardLabel:'YOUR PEOPLE, CONNECTED', cardTitle:'A check-in can mean so much.', icon:'users' },
  { id:'parking', number:'04', label:'Wrong parking', eyebrow:'VEHICLE QR · PARKING CONCERNS', title:['A blocked way.','An easier way','to connect.'], accent:2, description:'A car in the way? A window left open? A simple QR scan gives a helpful person a way to report the concern to the owner.', hindi:'गाड़ी रास्ते में है? स्कैन से बात आगे बढ़ाएँ।', cta:'See the parking flow', to:'/solutions/vehicle-safety', event:'A parked car needs attention', action:'Scan and report the concern', result:'Let the owner respond', cardLabel:'PARKING, MADE MORE CONSIDERATE', cardTitle:'A scan instead of a search.', icon:'car' },
  { id:'lost', number:'05', label:'Lost & found', eyebrow:'SMART QR · BAGS, BELONGINGS & MORE', title:['Lost somewhere.','Connected','somehow.'], accent:2, description:'A bag left behind. A suitcase mixed up. Give your everyday things a simple way to find their way back to you through a helpful finder.', hindi:'खोई हुई चीज़ को लौटने का एक रास्ता दें।', cta:'Discover Smart QR tags', to:'/solutions/smart-qr', event:'An item is left behind', action:'A finder scans its tag', result:'Make a helpful connection', cardLabel:'A WAY BACK TO YOU', cardTitle:'Small tag. Meaningful connection.', icon:'qr' },
];
export const solutionScene = {'personal-safety':'road','family-guardian':'family','smart-qr':'lost','vehicle-safety':'parking','anti-theft':'theft','digital-cards':'family','temporary-circles':'family','community-safety':'road'};
